# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

remote_theme: "mmistakes/minimal-mistakes@4.26.1"
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "Kurt's github.io"
title_separator          : "|"
name                     : &name "Kurt Waage" # &name is a YAML anchor which can be *referenced later
description              : "This site gives an overview of my experience and projects."
url                      : "https://kurtw.github.io"
words_per_minute         : 200
search                   : true # true, false (default)

# Site Author
author:
   name             : "Kurt Waage"
   avatar           : "assets/images/bio-photo.png"
   bio              : "My background is rooted in research and development, but my passion is games."
   location         : "Japan"
   email            :
   links:
      - label: "Email"
        icon: "fas fa-fw fa-envelope-square"
        url: "mailto:WaageFreelance@gmail.com"
      - label: "GitHub"
        icon: "fab fa-fw fa-github"
        url: "https://github.com/kurtw"
      - label: "LinkedIn"
        icon: "fab fa-fw fa-linkedin"
        url: "https://www.linkedin.com/in/kurt-j-waage/"
   
# Site Footer
footer:
   links:
      - label: "GitHub"
        icon: "fab fa-fw fa-github"
        url: "https://github.com/kurtw"
      - label: "LinkedIn"
        icon: "fab fa-fw fa-linkedin"
        url: "https://www.linkedin.com/in/kurt-j-waage/"
   
# Reading Files
include:
   - _pages
exclude:
   - "*.sublime-project"
   - "*.sublime-workspace"
   - vendor
   - .asset-cache
   - .bundle
   - .jekyll-assets-cache
   - .sass-cache
   - assets/js/plugins
   - assets/js/_main.js
   - assets/js/vendor
   - Capfile
   - CHANGELOG
   - config
   - Gemfile
   - Gruntfile.js
   - gulpfile.js
   - LICENSE
   - log
   - node_modules
   - package.json
   - package-lock.json
   - Rakefile
   - README
   - tmp


# Conversion
markdown: kramdown

# Markdown Processing
kramdown:
   input: GFM
   hard_wrap: false
   auto_ids: true
   footnote_nr: 1
   entity_output: as_char
   toc_levels: 1..6
   smart_quotes: lsquo,rsquo,ldquo,rdquo
   enable_coderay: false
   
# Collections
collections:
   portfolio:
      output: true
      permalink: /:collection/:path/
   games:
      output: true
      permalink: /:collection/:path/

# Defaults
defaults:
   # _posts
   - scope:
        path: ""
        type: posts
     values:
        layout: single
        author_profile: true
        read_time: true
        comments: true
        share: true
        related: true
   # _pages
   - scope:
        path: "_pages"
        type: pages
     values:
        layout: single
        author_profile: true
   # _portfolio
   - scope:
        path: ""
        type: portfolio
     values:
        layout: single
        author_profile: false
        share: true
   # _games
   - scope:
        path: ""
        type: games
     values:
        layout: single
        author_profile: false
        share: true

plugins:
   - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
